### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by Patricia-Moreira** [mestrode/IBS-Sensor-Library#1]
Hi, I'm having trouble calibrating the sensor. The calibration flag goes from 0 to 1 after 3/4 hours but the new capacity value stays the same as the initial capacity of the battery. This would be fine if the battery was new, but it isn't. It's more or less at 50% of it's initial capacity. Am i doing something wrong? Is there anyway you can help me? 

Thank you and congratulations for your work.
Kindest regards, 
Patricia

**Comment by mestrode** [comment]
Hi Patricia,

I love to hear from you, because that means you've taken a look at my code. Hope you enjoy it!

The IBS-Sensor observes the state of the battery by considering voltage and current. This means you have to put some load on the battery: This will effect a current flow and also some voltage drop on the internal resistance. Both is needed to indicating the current State of Health and  State of Charge. Without some load, there is too little information to observe, which prevents a valid estimate for SOH and SOC. As long as the sensor does not have any better idea, it simply stays at 100% values.
Since the available capacity is equal to configured capacity multiplied by SOC (%), this will cause you to see (temporary) wrong values.

Though I did also recognize the toggle of the calibration flag simply after some time including wrong values. Applying some current will cause an update on the estimated values. This should work regardless of writing a new configuration.

Additional minor info:
I've found and fixed a bug in the method writeUnknownParam(): The SensorId was fixed to "Sensor 2" devices, so a "Sensor 1" device was not able to receive the third config command (whose function is unknown).
Do you use a "Sensor 1" device? However, I guess this shouldn't have any effect.

**Comment by mestrode** [comment]
To be more precise: By some load I do mean  to apply an release some (may varying) currents. May 1% to 10% of the battery capacity - if this is possible in your setup. You should be able to observe some reaction at least after one minute. By time the estimated values will gain on validity.

Would be nice if you can send me some feedback. Hope your problem is solved!

**Comment by Patricia-Moreira** [comment]
Hello! Yes I'm using sensor 1. I will try doing the calibration with some load as you said during this week and I will give you an update in the next few days. 

Thank you for your quick response!

**Comment by Patricia-Moreira** [comment]
Hi mestrode,
I didn't manage to get it done. I did what you said and calibrated the battery with multiple loads between 1% and 10% of its initial capacity. I got the same results.
This is the circuit I'm using to test:

![Schematic](https://user-images.githubusercontent.com/99394523/205284783-6fc34072-61ab-427f-96f9-63477ee66d4f.png)

I'm using the tja1027 because the tja1021 is out of stock everywhere here. I checked the datasheet and they work the same way.
The oscilloscope results are fine, I think, and the rest of the values are okay too because they are the same as my voltage source shows. The IBS sensor I'm using is 6PK 010.842-001. 

![Oscilloscope](https://user-images.githubusercontent.com/99394523/205285049-cb59309c-3941-47bb-bb98-d1441030675a.jpeg)

Is there any way I can reset the sensor? 
Do you have any information or aditional documentation that you can provide in order to help me get it fixed?

Thank you!
Kindest regards,
Patricia

**Comment by mestrode** [comment]
Hey Patricia,

you Lin-Signals are looking good. I had understood your bus communication is working, since you can write config and read status?

However, the sensor needs some time for it's observations: After config (there is no load needed) the sensor starts the calibration. This is done by observing current and voltage over time. Hence periods without load, and also periods with several loads are containing different information, the estimation quality will be improved by showing different situations to the sensor. This is helpful to calculate the parameters of the battery model within the sensor.

Take a look into this pdf: https://www.hella.com/hella-cz/assets/media_global/IBS_Einbaustory_GB.pdf
>> After initial operation, the IBS has to collect measuring data first in order to be able to make a statement
about the exact state of charge of the battery after approx. 3 h.

When you don't apply some load  in the "learning" period, the sensor can only observe the standby voltage. This are fairly to less information for learning. Therefore the sensor does the best guess: "At least not empty" or in numbers no reason why this should not be 100%.

However, even after the calibration period all voltage and current information will improve the quality of SOH and SOC. You only have to config the sensor then you switch the battery. Even if the battery is empty: Simply charge and/or discharge the battery. The sensor will learn in all situations about the battery.

Hope this is more precise and will help you!
Best wishes!
